// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqzepbjyyqscvdevcukm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xemVwYmp5eXFzY3ZkZXZjdWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTQzMzIsImV4cCI6MjA2NzI5MDMzMn0.-8NxfgbwV5_y4TWIwpdWWKAgGcO_evW7hD_QI868Yxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});